apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multiplication
  namespace: team4
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: multiplication
    spec:
      containers:
      - name: multiplication
        image: jgensl2/multiplication-operator:v0.1.0
        ports:
        - name: operate
          containerPort: 8084
        command:
        - /a.out
        - -v=6
        - -logtostderr
        - -port=8084
