apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subtraction
  namespace: team3
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: subtraction
    spec:
      containers:
      - name: subtraction
        image: jgensl2/subtraction-operator:v0.1.0
        ports:
        - name: operate
          containerPort: 8083
        command:
        - /a.out
        - -v=6
        - -logtostderr
        - -port=8083
