apiVersion: v1
kind: Service
metadata:
  name: addition
  namespace: team2
  labels:
    app: addition
spec:
  ports:
  - port: 80
    targetPort: operate
    protocol: TCP
  selector:
    app: addition
