apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: team0
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: compute
    nodePort: 30888
    protocol: TCP
  selector:
    app: gateway
