apiVersion: v1
kind: Service
metadata:
  name: subtraction
  namespace: team3
  labels:
    app: subtraction
spec:
  ports:
  - port: 80
    targetPort: operate
    protocol: TCP
  selector:
    app: subtraction
