apiVersion: v1
kind: Service
metadata:
  name: tokenizer
  namespace: team1
  labels:
    app: tokenizer
spec:
  ports:
  - port: 80
    targetPort: tokenize
    protocol: TCP
  selector:
    app: tokenizer
